### ISSUE TITLE
No EndBackgroundTask Called

### ISSUE THREAD

**Issue by aarani** [nblockchain/XamarinFormsBackground#3]
deleted

**Comment by knocte** [comment]
Please open a new issue with structure (3 sections): steps to reproduce, expected results, current results (if you can't test this yourself because you don't have macOS/iOS, then instead of "current results" let's name it "potential bad results").

**Comment by knocte** [comment]
> as far as best practice goes I think we need to call EndBackgroundTask in Stop function and after our tasks are done, implementation example located here

Also, read again the handbook. That sentence above is not related to the bug, it's related to the potential solution. Therefore it should be written in a PR (not in the bug) or in a second comment.

**Comment by knocte** [comment]
> MSDN describes how to use Background Tasks in here

This info is not related to the bug either. It's part of the potential solution.

**Comment by knocte** [comment]
Sorry to be too formal with process but you will understand later that having attention to detail pays off :)
